//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crTb_Orders
    {
        public int ID_order { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_user { get; set; }
        public string Status { get; set; }
        public Nullable<int> ID_Company { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
    }
}
