//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Realstate_agentsEntities : DbContext
    {
        public Realstate_agentsEntities()
            : base("name=Realstate_agentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing_Shipping_details> Billing_Shipping_details { get; set; }
        public virtual DbSet<crTb_OrderDetails> crTb_OrderDetails { get; set; }
        public virtual DbSet<crTb_Orders> crTb_Orders { get; set; }
        public virtual DbSet<label_color> label_color { get; set; }
        public virtual DbSet<labels> labels { get; set; }
        public virtual DbSet<Market_Categ_type> Market_Categ_type { get; set; }
        public virtual DbSet<Marketing_order_details> Marketing_order_details { get; set; }
        public virtual DbSet<marketing_orders> marketing_orders { get; set; }
        public virtual DbSet<Payment_Intent> Payment_Intent { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<saved_labels> saved_labels { get; set; }
        public virtual DbSet<Saved_Templates> Saved_Templates { get; set; }
        public virtual DbSet<Shipping_Details> Shipping_Details { get; set; }
        public virtual DbSet<signs_description> signs_description { get; set; }
        public virtual DbSet<Sys_Company> Sys_Company { get; set; }
        public virtual DbSet<Sys_Notifications> Sys_Notifications { get; set; }
        public virtual DbSet<Sys_Roles> Sys_Roles { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<T_Company_Type> T_Company_Type { get; set; }
        public virtual DbSet<Tb_Appointments> Tb_Appointments { get; set; }
        public virtual DbSet<Tb_Conversation> Tb_Conversation { get; set; }
        public virtual DbSet<Tb_Customers> Tb_Customers { get; set; }
        public virtual DbSet<Tb_Customers_Users> Tb_Customers_Users { get; set; }
        public virtual DbSet<Tb_docCategies> Tb_docCategies { get; set; }
        public virtual DbSet<Tb_Docpackages> Tb_Docpackages { get; set; }
        public virtual DbSet<Tb_Docpackages_details> Tb_Docpackages_details { get; set; }
        public virtual DbSet<Tb_DocuAgent> Tb_DocuAgent { get; set; }
        public virtual DbSet<Tb_LeadDocs> Tb_LeadDocs { get; set; }
        public virtual DbSet<Tb_Marketing> Tb_Marketing { get; set; }
        public virtual DbSet<Tb_Message> Tb_Message { get; set; }
        public virtual DbSet<Tb_Network> Tb_Network { get; set; }
        public virtual DbSet<Tb_Notes> Tb_Notes { get; set; }
        public virtual DbSet<Tb_Options> Tb_Options { get; set; }
        public virtual DbSet<Tb_Posts> Tb_Posts { get; set; }
        public virtual DbSet<Tb_Process> Tb_Process { get; set; }
        public virtual DbSet<Tb_Quotes> Tb_Quotes { get; set; }
        public virtual DbSet<Tb_Reminders> Tb_Reminders { get; set; }
        public virtual DbSet<Tb_Resources> Tb_Resources { get; set; }
        public virtual DbSet<Tb_Reviews> Tb_Reviews { get; set; }
        public virtual DbSet<Tb_Source> Tb_Source { get; set; }
        public virtual DbSet<Tb_Status> Tb_Status { get; set; }
        public virtual DbSet<Tb_Tasks> Tb_Tasks { get; set; }
        public virtual DbSet<Tb_ToVerifyTaxes> Tb_ToVerifyTaxes { get; set; }
        public virtual DbSet<Tb_Videos> Tb_Videos { get; set; }
        public virtual DbSet<Tb_Webinars> Tb_Webinars { get; set; }
        public virtual DbSet<Tb_WorkTeams> Tb_WorkTeams { get; set; }
        public virtual DbSet<Template_categories> Template_categories { get; set; }
        public virtual DbSet<Template_colors> Template_colors { get; set; }
        public virtual DbSet<Template_Details> Template_Details { get; set; }
        public virtual DbSet<Template_dimensions> Template_dimensions { get; set; }
        public virtual DbSet<template_pricing> template_pricing { get; set; }
        public virtual DbSet<template_subcategories> template_subcategories { get; set; }
        public virtual DbSet<Template_type> Template_type { get; set; }
    }
}
