//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Appointments
    {
        public int ID_Appointment { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public int ID_Process { get; set; }
        public int ID_Customer { get; set; }
        public int ID_User { get; set; }
        public string Status { get; set; }
        public System.DateTime Date_end { get; set; }
        public int ID_Company { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
    }
}
