//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Customers_Users
    {
        public int Id_Customer_User { get; set; }
        public int Id_User { get; set; }
        public int Id_Customer { get; set; }
        public Nullable<int> ID_team { get; set; }
        public Nullable<bool> Teamleader { get; set; }
    }
}
