//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Docpackages_details
    {
        public int ID_Detail { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Notes { get; set; }
        public string Extension { get; set; }
        public string Size { get; set; }
        public bool original { get; set; }
        public bool uploaded { get; set; }
        public bool sent { get; set; }
        public bool mandatory { get; set; }
        public int ID_docpackage { get; set; }
    
        public virtual Tb_Docpackages Tb_Docpackages { get; set; }
    }
}
