//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Data
    {
        public int Id_file { get; set; }
        public byte[] Data { get; set; }
        public string Extension { get; set; }
        public string title { get; set; }
        public string FileName { get; set; }
        public string Category { get; set; }
        public bool Uploaded { get; set; }
        public int ID_customer { get; set; }
        public int ID_user { get; set; }
        public int ID_process { get; set; }
    
        public virtual Sys_Users Sys_Users { get; set; }
        public virtual Tb_Customers Tb_Customers { get; set; }
        public virtual Tb_Process Tb_Process { get; set; }
    }
}
