//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DocuAgent
    {
        public int Id_Document { get; set; }
        public string Doc_Name { get; set; }
        public string Url { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public Nullable<int> Id_User { get; set; }
        public string Extension { get; set; }
    
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
