//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Docpackages_details
    {
        public int ID_Detail { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Notes { get; set; }
        public string Extension { get; set; }
        public string Size { get; set; }
        public bool original { get; set; }
        public bool uploaded { get; set; }
        public bool sent { get; set; }
        public bool mandatory { get; set; }
        public Nullable<int> ID_docpackage { get; set; }
    
        public virtual Tb_Docpackages Tb_Docpackages { get; set; }
    }
}
