//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Docpackages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Docpackages()
        {
            this.Tb_Docpackages_details = new HashSet<Tb_Docpackages_details>();
        }
    
        public int ID_docpackage { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.DateTime Last_update { get; set; }
        public int Total_docs { get; set; }
        public int ID_User { get; set; }
        public int ID_Company { get; set; }
        public bool Active { get; set; }
        public bool original { get; set; }
        public int Total_docsf { get; set; }
        public bool Finished { get; set; }
        public bool Sent { get; set; }
        public int ID_Process { get; set; }
        public int ID_Customer { get; set; }
        public int ID_Property { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Docpackages_details> Tb_Docpackages_details { get; set; }
    }
}
