//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_docCategies
    {
        public int ID { get; set; }
        public int ID_Category { get; set; }
        public string Category_Title { get; set; }
        public string Title { get; set; }
        public bool Mandatory { get; set; }
    }
}
