//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Marketing
    {
        public int ID_marketing { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int Active { get; set; }
        public int Likes { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Type { get; set; }
        public int ID_Company { get; set; }
        public string Category { get; set; }
        public int Comments { get; set; }
        public string T_image { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
    }
}
