//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Message
    {
        public int ID_message { get; set; }
        public string Message_content { get; set; }
        public int User_ID { get; set; }
        public int ID_Conversation { get; set; }
        public System.DateTime Created_at { get; set; }
        public bool Is_read { get; set; }
    
        public virtual Tb_Conversation Tb_Conversation { get; set; }
    }
}
