//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Message
    {
        public int ID_message { get; set; }
        public string Message_content { get; set; }
        public int User_ID { get; set; }
        public int ID_Conversation { get; set; }
        public System.DateTime Created_at { get; set; }
        public bool Is_read { get; set; }
    
        public virtual Tb_Conversation Tb_Conversation { get; set; }
    }
}
