//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Notes
    {
        public int ID_note { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Property { get; set; }
        public int ID_Customer { get; set; }
        public int ID_User { get; set; }
        public string Created_By { get; set; }
    }
}
