//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Network
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Network()
        {
            this.Tb_Reviews = new HashSet<Tb_Reviews>();
        }
    
        public int ID_Network { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int Active { get; set; }
        public int Likes { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Type { get; set; }
        public int ID_Company { get; set; }
        public string Category { get; set; }
        public int Comments { get; set; }
        public string T_image { get; set; }
        public Nullable<bool> super_admin { get; set; }
        public string name_company { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Reviews> Tb_Reviews { get; set; }
    }
}
