//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Notes
    {
        public int ID_note { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Property { get; set; }
        public int ID_Customer { get; set; }
        public int ID_User { get; set; }
        public string Created_By { get; set; }
    
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
