//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Posts
    {
        public int ID_Post { get; set; }
        public string Title { get; set; }
        public string Content_post { get; set; }
        public string Url_image { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public System.DateTime Start_at { get; set; }
        public System.DateTime Finish_at { get; set; }
        public int Post_type { get; set; }
        public int ID_User { get; set; }
        public string Username { get; set; }
        public int Likes { get; set; }
        public string User_likes { get; set; }
        public int Comments { get; set; }
        public string User_comments { get; set; }
        public System.DateTime created_at { get; set; }
        public int Post_parent { get; set; }
        public bool Active { get; set; }
        public int ID_Company { get; set; }
    
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
