//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Quotes
    {
        public int ID_quote { get; set; }
        public string Text { get; set; }
        public string Author { get; set; }
        public bool Active { get; set; }
        public string Date { get; set; }
        public int ID_Company { get; set; }
    }
}
