//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Resources
    {
        public int ID_Resource { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Doc_type { get; set; }
        public System.DateTime Last_update { get; set; }
        public int Times_downloaded { get; set; }
        public int ID_Company { get; set; }
        public string Extension_file { get; set; }
        public Nullable<int> Id_Leader { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
    }
}
