//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Reviews
    {
        public int Id_Review { get; set; }
        public int Rate_Review { get; set; }
        public System.DateTime Date_Review { get; set; }
        public string Comment { get; set; }
        public int Id_Network { get; set; }
        public string Name_User { get; set; }
    
        public virtual Tb_Network Tb_Network { get; set; }
    }
}
