//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Reviews
    {
        public int Id_Review { get; set; }
        public int Rate_Review { get; set; }
        public System.DateTime Date_Review { get; set; }
        public string Comment { get; set; }
        public int Id_Network { get; set; }
        public string Name_User { get; set; }
    
        public virtual Tb_Network Tb_Network { get; set; }
    }
}
