//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Webinars
    {
        public int ID_Webinar { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public int Max_users { get; set; }
        public string Url { get; set; }
        public int Active { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public int ID_Company { get; set; }
        public string Category { get; set; }
        public string Url_video { get; set; }
        public System.DateTime Date_end { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
    }
}
