//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_WorkTeams
    {
        public int ID_team { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ID_Company { get; set; }
        public bool Active { get; set; }
        public System.DateTime Creation_date { get; set; }
        public System.DateTime Last_update { get; set; }
    }
}
